# --------- General Configs ---------
GENERAL:
  runner: 'LTSFTrainer'
  batch_size: 32
  max_epochs: 10
  early_stop_patience: 3


# --------- Data Configs ---------
DATA:
  in_steps: 96
  out_steps: 12
  x_time_of_day: True
  x_day_of_week: True
  y_time_of_day: False
  y_day_of_week: False


# --------- Test Configs ---------
TEST:
  input_mask:
    enabled: False
    ratio: 0.10
    steps: null
    repeats: 5


# --------- Training Configs ---------
OPTIM:
  loss: 'MSE'
  initial_lr: 0.001
  lr_scheduler_type: 'ExponentialLR'
  lr_scheduler_gamma: 0.5
  clip_grad: 5.0


# --------- Model Configs ---------
MODEL_PARAM:
  num_nodes: 170
  in_dim: 3
  layers: 3
  gcn_depth: 2
  subgraph_size: 20
  node_dim: 40
  tanhalpha: 3.0
  propalpha: 0.05
  dropout: 0.1
  dilation_exponential: 1
  residual_channels: 32
  conv_channels: 32
  skip_channels: 64
  end_channels: 128
