# --------- General Configs ---------
GENERAL:
  runner: 'LTSFTrainer'
  batch_size: 32
  max_epochs: 20
  early_stop_patience: 5


# --------- Data Configs ---------
DATA:
  in_steps: 96
  out_steps: 96
  x_time_of_day: False
  x_day_of_week: False
  y_time_of_day: False
  y_day_of_week: False


# --------- Test Configs ---------
TEST:
  input_mask:
    enabled: False
    ratio: 0.10
    steps: null
    repeats: 5


# --------- Training Configs ---------
OPTIM:
  loss: 'MSE'
  initial_lr: 0.001
  lr_scheduler_type: 'ExponentialLR'
  lr_scheduler_gamma: 0.5


# --------- Model Configs ---------
MODEL_PARAM:
  num_nodes: 500
  individual: False
  kernel_size: 25
