# --------- General Configs ---------
GENERAL:
  runner: 'LTSFTrainer'
  batch_size: 32
  max_epochs: 10
  early_stop_patience: 3


# --------- Data Configs ---------
DATA:
  in_steps: 96
  out_steps: 48
  x_time_of_day: False
  x_day_of_week: False
  y_time_of_day: False
  y_day_of_week: False


# --------- Test Configs ---------
TEST:
  input_mask:
    enabled: True
    ratio: null
    steps: 24
    repeats: 1


# --------- Training Configs ---------
OPTIM:
  loss: 'MSE'
  initial_lr: 0.001
  lr_scheduler_type: 'ExponentialLR'
  lr_scheduler_gamma: 0.5 
  clip_grad: 5.0


# --------- Model Configs ---------
MODEL_PARAM:
  seq_len_in: 96
  seq_len_out: 48
  num_nodes: 500
  d_model: 512
  d_ff: 512
  use_revin: False
  dropout: 0.1  
  std_kernel: 25
  e_layers: 2
  d_state: 32
  d_conv: 2
  expand: 1
  activation: 'gelu'
  ds_type: 'avg'
  ds_layers: 3
  ds_window: 2