# --------- General Configs ---------
GENERAL:
  runner: 'LTSFTrainer'
  batch_size: 32
  max_epochs: 20
  early_stop_patience: 5


# --------- Data Configs ---------
DATA:
  in_steps: 96
  out_steps: 48
  x_time_of_day: True
  x_day_of_week: True
  y_time_of_day: False
  y_day_of_week: False


# --------- Test Configs ---------
TEST:
  input_mask:
    enabled: False
    ratio: 0.10
    steps: null
    repeats: 5


# --------- Training Configs ---------
OPTIM:
  loss: 'MSE'
  initial_lr: 0.001
  lr_scheduler_type: 'ExponentialLR'
  lr_scheduler_gamma: 0.5


# --------- Model Configs ---------
MODEL_PARAM:
  num_nodes: 307
  cycle_len: 288
  cycle_pattern: 'daily&weekly'
  use_revin: True
  d_model: 512
  d_ff: 512
  d_state: 32
  d_conv: 2
  d_conv_2: 4
  expand: 1
  dropout: 0.1
  e_layers: 2
  mamba_type: 'mamba'
  block_type: 'mhc'
  num_streams: 2
  period_len: 12
  lpf: 5
  gtr_mode: 'slim'
  use_joint: True
  joint_rank: 8
